language: java
env:
  global:
  - CC_TEST_REPORTER_ID=3f1c0d93a3be444be021f93bdb077079ae9acee47374681435d9292821f4fe0c
before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"
script:
- mvn test
after_script:
- "./cc-test-reporter format-coverage -d -t jacoco ./target/jacoco-ut/jacoco.xml"
- "./cc-test-reporter upload-coverage -d"
before_deploy:
- mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
- export project_version=$(mvn help:evaluate -N -Dexpression=project.version|grep
  -v '\[')
deploy:
  provider: releases
  api_key:
    secure: AIsVIVXvqgHfRUzsZgsUxsKPhAorz1ir6nKWzifTnp1fKqNpL8Pq7YkQCk3oT5NK17ifwZJtPgCZIimm31h7UuRHpd9bezje8HiDD7X0k1mPyeHAQox67OYPwmL951SeWnmxToAZSrn3xUlwRfonPbYaeDPA+XtcV1xwOF5MnK8n6Zo2nKuKfV0LLr6MOuDshtcMafsvP36+8JOulbGRrmGh8LNN9/4PPY6CPSNx+aDaGvJvySGhQjG9xnBpKTG/xleZQDyCdcNBs1ZZFEIA/yMyq0hHLmnkiO/VU3oqDoO0MPCOxyKsS4r2MNMH8AOr9dLV88cb9YKXe38KnCcamjzs4RLGCY2azSpzcAVMjihHI1VqjrBrfHV6CXlLP0xB4QDr8WmyBR2zYa4C6prUBAISiZT/MYZW7f19E/vi8rL7+fA/4a/bzkn9mQTOC1e8mrX2lkFvu3mRdP3yCYbAGDGM0XXW7hyT3Y1KG3tnJgQxEJlrQxIvkC3YE+szCXB7Q7cPDkmhXArU4Mz0HMyVD/XaAo8w+ScQDKr6ffL57wNZVut3YcSr+RALhbfMwwwQq6sgPeFNFuQXMpEhQv1goRDYsr2RacpR6iiKPcv66sMsRmxjr/bAf4uqQukr4wIUFONOrZbM+bx0s8iKN3jLBN/h+aE1SqeBXJvTrVyZslg=
  file: ".travis.yml"
  on:
    repo: trickl/sort
